(() => {
  "use strict";
  const API=(window.POKEMAP_CONFIG?.apiBase||"").replace(/\/$/,"");
  const CONFIG=window.POKEMAP_CONFIG||{};
  const REPORT_API=(CONFIG.reportApiBase||API).replace(/\/$/,"");
  const NIANTIC_QUERY=`query MapFallback($input: RealityChannelMapObjectsByS2CellsInput!) { realityChannelMapObjectsByS2Cells(input: $input) { mapObjectsByS2CellsAndTypes { s2CellId mapObjectsByType { type mapObjects { id pgoGym { name location { latitude longitude } } pgoPokestop { name location { latitude longitude } } } } } } }`;
  const nianticCache=new Map();
  const state={mode:"research",pois:[],submissions:[],catalogue:[],selected:null,planPoint:null};
  const savedView=loadSavedView();
  const map=L.map("map",{zoomControl:false}).setView([savedView.latitude,savedView.longitude],savedView.zoom);
  L.control.zoom({position:"bottomright"}).addTo(map);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  const poiLayer=L.layerGroup(),plans=L.layerGroup(),cells17=L.layerGroup(),cells14=L.layerGroup();
  map.addLayer(poiLayer);map.addLayer(plans);map.addLayer(cells17);map.addLayer(cells14);
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const escape=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const api=async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.status===204?null:r.json()};
  const reportApi=async(path,options={})=>{const r=await fetch(REPORT_API+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.status===204?null:r.json()};
  function loadSavedView(){try{const view=JSON.parse(localStorage.getItem("pokemap-view-v1"));if(Number.isFinite(view?.latitude)&&view.latitude>=-90&&view.latitude<=90&&Number.isFinite(view?.longitude)&&view.longitude>=-180&&view.longitude<=180&&Number.isInteger(view?.zoom)&&view.zoom>=3&&view.zoom<=20)return view}catch{}return{latitude:51.2194,longitude:4.4025,zoom:14}}
  function saveView(){try{const center=map.getCenter();localStorage.setItem("pokemap-view-v1",JSON.stringify({latitude:center.lat,longitude:center.lng,zoom:map.getZoom()}))}catch{}}
  function typeOf(p){return String(p.type||"").toUpperCase().replace(/[É_ ]/g,c=>c==="É"?"E":"")}
  function icon(type,planned=false){const key=planned?"planned":type==="POKESTOP"?"stop":type==="GYM"?"gym":"power";return L.divIcon({className:"",html:`<div class="${planned?"plan-icon":"poi-icon"} ${key}"><span>${planned?"＋":type==="GYM"?"★":type==="POWERSPOT"?"⚡":"●"}</span></div>`,iconSize:[29,29],iconAnchor:[14,28]})}
  function directions(lat,lng){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lat+","+lng)}`}
  function renderPois(){poiLayer.clearLayers();const q=$("#search").value.trim().toLowerCase(),enabled=new Set($$("[data-filter]:checked").map(x=>x.dataset.filter));for(const p of state.pois){const t=typeOf(p);if(!enabled.has(t)||q&&!p.name.toLowerCase().includes(q))continue;L.marker([p.latitude,p.longitude],{icon:icon(t)}).on("click",()=>openPoi(p)).addTo(poiLayer)}}
  function renderPlans(){plans.clearLayers();if(state.mode!=="planner"||!$("#plannedFilter").checked)return;for(const p of state.submissions)L.marker([p.latitude,p.longitude],{icon:icon("",true)}).on("click",()=>openPlan(p)).addTo(plans)}
  async function openPoi(p){state.selected=p;let candidates=[];if(typeOf(p)==="POKESTOP")try{candidates=await reportApi(`/api/research?pokestopId=${encodeURIComponent(p.id)}`)}catch(e){toast(e.message)}const quests=candidates.length?candidates.map(c=>`<div class="quest"><strong>${escape(taskName(c.taskId))}</strong><span>${escape(rewardName(c.taskId,c.rewardId))} · ${c.confirmationCount} confirmation${c.confirmationCount===1?"":"s"}${c.needsReview?" · ⚠ conflict":""}</span></div>`).join(""):`<p>No research has been reported here today.</p>`;$("#sheetContent").innerHTML=`<span class="badge">${escape(typeOf(p))}</span><h2>${escape(p.name||"Unnamed Wayspot")}</h2>${typeOf(p)==="POKESTOP"?quests:"<p>Field Research can only be attached to PokéStops.</p>"}<div class="sheet-actions"><a href="${directions(p.latitude,p.longitude)}" target="_blank" rel="noopener">Directions</a>${typeOf(p)==="POKESTOP"?'<button id="reportHere" class="primary">Report research</button>':""}</div>`;showSheet();$("#reportHere")?.addEventListener("click",openReport)}
  function openPlan(p){$("#sheetContent").innerHTML=`<span class="badge">${escape(p.status)}</span><h2>${escape(p.proposedTitle||"Planned Wayspot")}</h2><p>${escape(p.notes||"No notes")}</p><div class="quest"><strong>S2 Level 17</strong><span>${escape(p.s2Level17Id)}</span><strong>S2 Level 14</strong><span>${escape(p.s2Level14Id)}</span></div><div class="sheet-actions"><a href="${directions(p.latitude,p.longitude)}" target="_blank" rel="noopener">Directions</a><button id="reportSpam">Report spam</button></div>`;showSheet();$("#reportSpam").addEventListener("click",async()=>{try{await api(`/api/submissions/${p.id}/spam`,{method:"POST"});toast("Sent to moderators")}catch(e){toast(e.message)}})}
  function showSheet(){$("#sheet").classList.add("open");$("#sheetBackdrop").classList.remove("hidden")}function closeSheet(){$("#sheet").classList.remove("open");$("#sheetBackdrop").classList.add("hidden")}
  function plainText(value){const el=document.createElement("span");el.innerHTML=String(value??"");return el.textContent.trim()}
  function slug(value){return String(value).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
  function taskName(id){return plainText(state.catalogue.find(t=>t.id===id)?.text||id)}function rewardName(tid,rid){return state.catalogue.find(t=>t.id===tid)?.rewards.find(r=>r.id===rid)?.label||rid}
  function fillTasks(){$("#taskSelect").innerHTML=state.catalogue.map(t=>`<option value="${escape(t.id)}">${escape(plainText(t.text))}</option>`).join("");fillRewards()}function fillRewards(){const t=state.catalogue.find(t=>t.id===$("#taskSelect").value);$("#rewardSelect").innerHTML=(t?.rewards||[]).map(r=>`<option value="${escape(r.id)}">${escape(r.label)}</option>`).join("")}
  let turnstileWidget;
  async function openReport(){closeSheet();$("#reportStop").textContent=state.selected.name;fillTasks();$("#reportDialog").showModal();if(CONFIG.turnstileSiteKey){$("#turnstileContainer").classList.remove("hidden");for(let i=0;i<30&&!window.turnstile;i++)await new Promise(resolve=>setTimeout(resolve,100));if(window.turnstile){if(turnstileWidget===undefined)turnstileWidget=turnstile.render("#turnstileContainer",{sitekey:CONFIG.turnstileSiteKey,theme:"dark"});else turnstile.reset(turnstileWidget)}}}
  async function loadVisible(){const b=map.getBounds();try{state.pois=await api(`/api/pois?minLat=${b.getSouth()}&maxLat=${b.getNorth()}&minLng=${b.getWest()}&maxLng=${b.getEast()}`);renderPois();if(state.mode==="planner")loadCells()}catch(e){if(!CONFIG.nianticFrontendFallback){warn(e.message);return}try{state.pois=await loadNianticPois(b);renderPois();warn("Testing fallback active · data comes directly from Niantic GraphQL · Power Spots unavailable");if(state.mode==="planner")loadCells()}catch(fallbackError){warn(`POI API failed · GraphQL fallback failed: ${fallbackError.message}`)}}}
  async function loadNianticPois(bounds){
    const ids=frontendS2CellIds(bounds);
    if(!ids.length||ids.length>128)throw new Error("zoom in before using the fallback");const cacheKey=ids.slice().sort().join(","),cached=nianticCache.get(cacheKey);if(cached&&cached.expires>Date.now())return cached.pois.filter(p=>bounds.contains([p.latitude,p.longitude]));
    const sourcesByS2Cells=ids.map(s2CellId=>({s2CellId,sources:[{name:"PGO",dropTypes:["PGO_GYM","PGO_POKESTOP"]}]}));
    const response=await fetch(CONFIG.nianticGraphqlUrl,{method:"POST",mode:"cors",credentials:"omit",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:NIANTIC_QUERY,variables:{input:{realityChannelId:CONFIG.nianticRealityChannelId,s2CellLevel:14,sourcesByS2Cells}}})});
    if(!response.ok)throw new Error(`Niantic returned HTTP ${response.status}`);const payload=await response.json();if(payload.errors?.length)throw new Error("Niantic returned GraphQL errors");const rows=payload.data?.realityChannelMapObjectsByS2Cells?.mapObjectsByS2CellsAndTypes;if(!Array.isArray(rows))throw new Error("unexpected Niantic response");
    const found=new Map(),seen=new Date().toISOString();for(const cell of rows)for(const group of cell.mapObjectsByType||[]){const type=group.type==="PGO_GYM"?"GYM":group.type==="PGO_POKESTOP"?"POKESTOP":null;if(!type)continue;const field=type==="GYM"?"pgoGym":"pgoPokestop";for(const object of group.mapObjects||[]){const data=object[field],location=data?.location;if(!object.id||!location)continue;const p={id:object.id,type,name:data.name||`Unnamed ${type}`,latitude:Number(location.latitude),longitude:Number(location.longitude),lastSeen:seen,s2Level17:"",s2Level14:BigInt(cell.s2CellId).toString(16).replace(/0+$/,"")};found.set(p.id,p)}}const pois=[...found.values()];nianticCache.set(cacheKey,{expires:Date.now()+120000,pois});if(nianticCache.size>20)nianticCache.delete(nianticCache.keys().next().value);return pois.filter(p=>bounds.contains([p.latitude,p.longitude]))
  }
  function frontendS2CellIds(bounds){if(!window.S2?.latLngToKey)throw new Error("S2 browser library did not load");const latSpan=bounds.getNorth()-bounds.getSouth(),lngSpan=bounds.getEast()-bounds.getWest();const rows=Math.max(1,Math.ceil(latSpan/.002)),cols=Math.max(1,Math.ceil(lngSpan/.003));if(rows>60||cols>60)throw new Error("zoom in before using the fallback");const ids=new Set();for(let y=0;y<=rows;y++)for(let x=0;x<=cols;x++){const lat=bounds.getSouth()+latSpan*y/rows,lng=bounds.getWest()+lngSpan*x/cols;ids.add(S2.keyToId(S2.latLngToKey(lat,lng,14)))}return [...ids]}
  async function loadCells(){const b=map.getBounds(),qs=`minLat=${b.getSouth()}&maxLat=${b.getNorth()}&minLng=${b.getWest()}&maxLng=${b.getEast()}`;for(const [level,layer,color,box] of [[17,cells17,"#4dbdff","#l17"],[14,cells14,"#ffbd59","#l14"]]){layer.clearLayers();if(!$(box).checked)continue;try{const rows=await api(`/api/s2/cells?${qs}&level=${level}`);rows.forEach(c=>L.polygon(c.polygon,{color,weight:level===17?1:2,fillOpacity:0,opacity:level===17?.45:.8,interactive:false}).addTo(layer))}catch(e){if(level===17)warn(e.message)}}}
  async function loadStatic(){let catalogue;try{catalogue=await reportApi("/api/research/catalogue")}catch{try{catalogue={tasks:await loadScrapedDuckCatalogue(),stale:false};toast("Tasks loaded directly from ScrapedDuck")}catch(e){warn(`Task catalogue unavailable · ${e.message}`)}}if(catalogue?.tasks?.length)state.catalogue=catalogue.tasks;try{const stats=await reportApi("/api/stats");const nums=[stats.reports_submitted,stats.unique_pokestops_reported,stats.confirmations,stats.conflicting_reports];$$('#stats strong').forEach((el,i)=>el.textContent=nums[i]||0);$("#progressButton").textContent=`Today · ${stats.unique_pokestops_reported||0} stops`}catch(e){if(!state.catalogue.length)warn(`Report service unavailable · ${e.message}`)}try{state.submissions=await api("/api/submissions");renderPlans()}catch{}}
  async function loadScrapedDuckCatalogue(){const cacheKey="pokemap-research-catalogue-v1";try{const response=await fetch(CONFIG.scrapedDuckResearchUrl,{cache:"no-store",credentials:"omit"});if(!response.ok)throw new Error(`ScrapedDuck returned HTTP ${response.status}`);const rows=await response.json();if(!Array.isArray(rows))throw new Error("unexpected ScrapedDuck response");const tasks=rows.map((row,index)=>{const raw=String(row.text||"").trim(),seen=new Set();const rewards=(Array.isArray(row.rewards)?row.rewards:[]).map(reward=>{const label=String(reward.name||reward.label||"").trim(),id=slug(label);if(!label||!id||seen.has(id))return null;seen.add(id);return{id,label,type:"ENCOUNTER"}}).filter(Boolean);return raw&&rewards.length?{id:`${slug(raw)}-${index}`,text:plainText(raw),category:"research",rewards}:null}).filter(Boolean);if(!tasks.length)throw new Error("ScrapedDuck returned no tasks");localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),tasks}));return tasks}catch(error){try{const cached=JSON.parse(localStorage.getItem(cacheKey));if(cached?.tasks?.length)return cached.tasks}catch{}throw error}}
  function warn(text){$("#warning").textContent=text;$("#warning").classList.remove("hidden")}function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
  let moveTimer;map.on("moveend",()=>{saveView();clearTimeout(moveTimer);moveTimer=setTimeout(loadVisible,250)});map.on("click",e=>{if(state.mode!=="planner")return;state.planPoint=e.latlng;$("#coordinates").textContent=`${e.latlng.lat.toFixed(6)}, ${e.latlng.lng.toFixed(6)}`;$("#planDialog").showModal()});
  $$(".modes button").forEach(b=>b.addEventListener("click",()=>{$$(".modes button").forEach(x=>x.classList.toggle("active",x===b));state.mode=b.dataset.mode;document.body.classList.toggle("planner",state.mode==="planner");$("#modeTitle").textContent=state.mode==="planner"?"Plan future Wayspots":"Find today’s research";$("#modeCopy").textContent=state.mode==="planner"?"Tap the map to add a planned submission and inspect S2 cells.":"Tap a PokéStop to view or report its current Field Research.";closeSheet();renderPlans();loadCells()}));
  $$("[data-filter],#plannedFilter,#l17,#l14").forEach(x=>x.addEventListener("change",()=>{renderPois();renderPlans();loadCells()}));$("#search").addEventListener("input",renderPois);$("#sheetBackdrop").addEventListener("click",closeSheet);$("#taskSelect").addEventListener("change",fillRewards);$("#refresh").addEventListener("click",()=>{loadVisible();loadStatic()});
  $("#locate").addEventListener("click",()=>map.locate({setView:true,maxZoom:17,enableHighAccuracy:true}));map.on("locationerror",()=>toast("Location unavailable — showing Antwerp"));
  $("#submitReport").addEventListener("click",async e=>{e.preventDefault();try{const turnstileToken=turnstileWidget===undefined?null:turnstile.getResponse(turnstileWidget);await reportApi("/api/research/report",{method:"POST",body:JSON.stringify({pokestopId:state.selected.id,taskId:$("#taskSelect").value,rewardId:$("#rewardSelect").value,latitude:state.selected.latitude,longitude:state.selected.longitude,turnstileToken})});$("#reportDialog").close();toast("Research reported — thank you!");loadStatic();openPoi(state.selected)}catch(err){toast(err.message);if(turnstileWidget!==undefined)turnstile.reset(turnstileWidget)}});
  $("#submitPlan").addEventListener("click",async e=>{e.preventDefault();try{const p=await api("/api/submissions",{method:"POST",body:JSON.stringify({latitude:state.planPoint.lat,longitude:state.planPoint.lng,proposedTitle:$("#planTitle").value||null,notes:$("#planNotes").value||null})});$("#planDialog").close();state.submissions.unshift(p);renderPlans();openPlan(p);toast("Planned Wayspot saved")}catch(err){toast(err.message)}});
  loadVisible();loadStatic();
})();
