(() => {
  "use strict";
  const API=(window.POKEMAP_CONFIG?.apiBase||"").replace(/\/$/,"");
  const CONFIG=window.POKEMAP_CONFIG||{};
  const REPORT_API=(CONFIG.reportApiBase||API).replace(/\/$/,"");
  const NIANTIC_QUERY=`query MapFallback($input: RealityChannelMapObjectsByS2CellsInput!) { realityChannelMapObjectsByS2Cells(input: $input) { mapObjectsByS2CellsAndTypes { s2CellId mapObjectsByType { type mapObjects { id pgoGym { name location { latitude longitude } } pgoPokestop { name location { latitude longitude } } } } } } }`;
  const nianticCache=new Map();
  const state={mode:"research",pois:[],catalogue:[],reportsByStop:new Map(),questFilter:loadQuestFilter(),selected:null};
  const savedView=loadSavedView();
  const map=L.map("map",{zoomControl:false}).setView([savedView.latitude,savedView.longitude],savedView.zoom);
  L.control.zoom({position:"bottomright"}).addTo(map);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  const poiLayer=L.layerGroup(),radiusLayer=L.layerGroup(),cells17=L.layerGroup(),cells14=L.layerGroup(),cellRenderer=L.canvas({padding:.5});
  map.addLayer(radiusLayer);map.addLayer(cells17);map.addLayer(cells14);map.addLayer(poiLayer);
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const escape=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const api=async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.status===204?null:r.json()};
  const reportApi=async(path,options={})=>{const r=await fetch(REPORT_API+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.status===204?null:r.json()};
  function loadSavedView(){try{const view=JSON.parse(localStorage.getItem("pokemap-view-v1"));if(Number.isFinite(view?.latitude)&&view.latitude>=-90&&view.latitude<=90&&Number.isFinite(view?.longitude)&&view.longitude>=-180&&view.longitude<=180&&Number.isInteger(view?.zoom)&&view.zoom>=3&&view.zoom<=20)return view}catch{}return{latitude:51.2194,longitude:4.4025,zoom:14}}
  function saveView(){try{const center=map.getCenter();localStorage.setItem("pokemap-view-v1",JSON.stringify({latitude:center.lat,longitude:center.lng,zoom:map.getZoom()}))}catch{}}
  function loadQuestFilter(){try{const saved=JSON.parse(localStorage.getItem("pokemap-quest-filter-v1"));if(saved&&Array.isArray(saved.selected))return{active:Boolean(saved.active),selected:new Set(saved.selected.map(String)),showUnreported:saved.showUnreported!==false}}catch{}return{active:false,selected:new Set(),showUnreported:true}}
  function saveQuestFilter(){try{localStorage.setItem("pokemap-quest-filter-v1",JSON.stringify({active:state.questFilter.active,selected:[...state.questFilter.selected],showUnreported:state.questFilter.showUnreported}))}catch{}}
  const questKey=report=>`${report.taskId}::${report.rewardId}`;
  function typeOf(p){return String(p.type||"").toUpperCase().replace(/[É_ ]/g,c=>c==="É"?"E":"")}
  function icon(type,reward){if(type==="POKESTOP"&&reward?.image)return L.divIcon({className:"",html:`<div class="reward-icon"><img src="${escape(reward.image)}" alt="${escape(reward.label)}" loading="lazy" decoding="async">${reward.conflict?'<span class="reward-conflict">!</span>':""}</div>`,iconSize:[50,50],iconAnchor:[25,25],popupAnchor:[0,-27]});const key=type==="GYM"?"gym":"stop";return L.divIcon({className:"",html:`<div class="poi-icon ${key}"><span>${type==="GYM"?"★":"●"}</span></div>`,iconSize:[29,29],iconAnchor:[14,28]})}
  function directions(lat,lng){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lat+","+lng)}`}
  function reportsForStop(stopId){const reports=state.reportsByStop.get(stopId)||[];return state.questFilter.active?reports.filter(report=>state.questFilter.selected.has(questKey(report))):reports}
  function rewardForStop(stopId){const allReports=state.reportsByStop.get(stopId)||[],reports=reportsForStop(stopId);if(!reports.length)return null;const best=[...reports].sort((a,b)=>(b.confirmationCount||0)-(a.confirmationCount||0)||String(b.lastReportedAt||"").localeCompare(String(a.lastReportedAt||"")))[0],reward=state.catalogue.find(task=>task.id===best.taskId)?.rewards.find(item=>item.id===best.rewardId);return reward?.image?{image:reward.image,label:reward.label,conflict:allReports.length>1||allReports.some(report=>report.needsReview)}:null}
  function passesQuestFilter(p,type){if(type!=="POKESTOP")return true;const reports=state.reportsByStop.get(p.id)||[];return reports.length?reportsForStop(p.id).length>0:state.questFilter.showUnreported}
  function renderPois(){poiLayer.clearLayers();const q=$("#search").value.trim().toLowerCase(),enabled=new Set($$("[data-filter]:checked").map(x=>x.dataset.filter)),detailed=map.getZoom()>=16;for(const p of state.pois){const t=typeOf(p);if(t==="GYM"&&state.mode!=="planner"||!enabled.has(t)||!passesQuestFilter(p,t)||q&&!p.name.toLowerCase().includes(q))continue;const reward=rewardForStop(p.id),marker=reward||detailed?L.marker([p.latitude,p.longitude],{icon:icon(t,reward),title:p.name}):L.circleMarker([p.latitude,p.longitude],{renderer:cellRenderer,radius:t==="GYM"?6:5,color:"#eafcff",weight:2,fillColor:t==="GYM"?"#e84b57":"#168ee3",fillOpacity:1});marker.on("click",()=>openPoi(p)).addTo(poiLayer)}renderRadii()}
  function renderRadii(){radiusLayer.clearLayers();if(state.mode!=="planner"||map.getZoom()<15||!$("#radius20").checked)return;const q=$("#search").value.trim().toLowerCase(),enabled=new Set($$("[data-filter]:checked").map(x=>x.dataset.filter));for(const p of state.pois){const type=typeOf(p);if(!enabled.has(type)||!passesQuestFilter(p,type)||q&&!p.name.toLowerCase().includes(q))continue;L.circle([p.latitude,p.longitude],{renderer:cellRenderer,radius:20,color:"#52e0a4",weight:1,opacity:.9,fillColor:"#52e0a4",fillOpacity:.12,interactive:false}).addTo(radiusLayer)}}
  async function openPoi(p){state.selected=p;let candidates=[];if(typeOf(p)==="POKESTOP")try{candidates=await reportApi(`/api/research?pokestopId=${encodeURIComponent(p.id)}`)}catch(e){toast(e.message)}const quests=candidates.length?candidates.map(c=>`<div class="quest"><strong>${escape(taskName(c.taskId))}</strong><span>${escape(rewardName(c.taskId,c.rewardId))} · ${c.confirmationCount} confirmation${c.confirmationCount===1?"":"s"}${c.needsReview?" · ⚠ conflict":""}</span></div>`).join(""):`<p>No research has been reported here today.</p>`;$("#sheetContent").innerHTML=`<span class="badge">${escape(typeOf(p))}</span><h2>${escape(p.name||"Unnamed Wayspot")}</h2>${typeOf(p)==="POKESTOP"?quests:"<p>Field Research can only be attached to PokéStops.</p>"}<div class="sheet-actions"><a href="${directions(p.latitude,p.longitude)}" target="_blank" rel="noopener">Directions</a>${typeOf(p)==="POKESTOP"?'<button id="reportHere" class="primary">Report research</button>':""}</div>`;showSheet();$("#reportHere")?.addEventListener("click",openReport)}
  function showSheet(){$("#sheet").classList.add("open");$("#sheetBackdrop").classList.remove("hidden")}function closeSheet(){$("#sheet").classList.remove("open");$("#sheetBackdrop").classList.add("hidden")}
  function plainText(value){const el=document.createElement("span");el.innerHTML=String(value??"");return el.textContent.trim()}
  function slug(value){return String(value).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
  function taskName(id){return plainText(state.catalogue.find(t=>t.id===id)?.text||id)}function rewardName(tid,rid){return state.catalogue.find(t=>t.id===tid)?.rewards.find(r=>r.id===rid)?.label||rid}
  function fillTasks(){$("#taskSelect").innerHTML=state.catalogue.map(t=>`<option value="${escape(t.id)}">${escape(plainText(t.text))}</option>`).join("");fillRewards()}function fillRewards(){const t=state.catalogue.find(t=>t.id===$("#taskSelect").value);$("#rewardSelect").innerHTML=(t?.rewards||[]).map(r=>`<option value="${escape(r.id)}">${escape(r.label)}</option>`).join("")}
  function updateQuestFilterButton(){const active=state.questFilter.active||!state.questFilter.showUnreported;$("#questFilterButton").classList.toggle("active",active);$("#questFilterButton").title=active?"Quest filters active":"Filter reported quests"}
  function taskKeys(box){return box.dataset.questKeys.split("|").filter(Boolean)}
  function syncRewardGroups(){$$('.reward-filter-group').forEach(group=>{const parent=group.querySelector('[data-reward-key]'),children=[...group.querySelectorAll('[data-quest-keys]')],checked=children.filter(box=>box.checked).length,partial=children.some(box=>box.indeterminate);parent.checked=checked===children.length&&!partial;parent.indeterminate=partial||checked>0&&checked<children.length})}
  function applyQuestFilters(){const boxes=$$("#questFilterOptions [data-quest-keys]"),selected=new Set();for(const box of boxes)if(box.checked)for(const key of taskKeys(box))selected.add(key);else if(box.indeterminate)for(const key of taskKeys(box))if(state.questFilter.selected.has(key))selected.add(key);state.questFilter.selected=selected;state.questFilter.active=boxes.some(box=>!box.checked||box.indeterminate);state.questFilter.showUnreported=$("#showUnreported").checked;saveQuestFilter();syncRewardGroups();updateQuestFilterButton();renderPois()}
  function filterQuestOptions(){const query=$("#questFilterSearch").value.trim().toLowerCase();$$('.reward-filter-group').forEach(group=>group.classList.toggle("hidden",query&&!group.dataset.filterText.includes(query)))}
  function renderQuestFilters(){
    const reportedRewards=new Map();for(const reports of state.reportsByStop.values())for(const report of reports){const entry=reportedRewards.get(report.rewardId)||{reports:0,examples:[]};entry.reports++;entry.examples.push(report);reportedRewards.set(report.rewardId,entry)}
    const groups=[];for(const [rewardId,activity] of reportedRewards){const tasks=[];let reward=null;for(const task of state.catalogue){const match=task.rewards?.find(item=>item.id===rewardId);if(match){reward||=match;tasks.push({text:plainText(task.text),key:`${task.id}::${rewardId}`})}}if(!reward){const example=activity.examples[0];reward={id:rewardId,label:rewardName(example.taskId,rewardId)}}const known=new Set(tasks.map(task=>task.key));for(const report of activity.examples){const key=questKey(report);if(!known.has(key)){known.add(key);tasks.push({text:taskName(report.taskId),key})}}const combined=new Map();for(const task of tasks){const textKey=task.text.toLocaleLowerCase("en");if(!combined.has(textKey))combined.set(textKey,{text:task.text,keys:[]});combined.get(textKey).keys.push(task.key)}const uniqueTasks=[...combined.values()].sort((a,b)=>a.text.localeCompare(b.text));groups.push({reward,activity,tasks:uniqueTasks})}
    groups.sort((a,b)=>a.reward.label.localeCompare(b.reward.label));$("#showUnreported").checked=state.questFilter.showUnreported;
    $("#questFilterOptions").innerHTML=groups.length?groups.map(group=>{const image=group.reward.image?`<img src="${escape(group.reward.image)}" alt="" loading="lazy" decoding="async">`:"";const taskText=group.tasks.map(task=>task.text).join(" ").toLowerCase();return`<details class="reward-filter-group" data-filter-text="${escape(`${group.reward.label} ${taskText}`.toLowerCase())}"><summary><input type="checkbox" data-reward-key="${escape(group.reward.id)}"><span class="reward-summary-image">${image}</span><span><strong>${escape(group.reward.label)}</strong><small>${group.tasks.length} potential task${group.tasks.length===1?"":"s"} · ${group.activity.reports} report${group.activity.reports===1?"":"s"}</small></span></summary><div class="potential-task-list">${group.tasks.map(task=>{const selected=task.keys.filter(key=>state.questFilter.selected.has(key)).length,checked=!state.questFilter.active||selected===task.keys.length,partial=state.questFilter.active&&selected>0&&selected<task.keys.length;return`<label><input type="checkbox" data-quest-keys="${escape(task.keys.join("|"))}" data-partial="${partial}" ${checked?"checked":""}><span>${escape(task.text)}</span></label>`}).join("")}</div></details>`}).join(""):'<p class="filter-empty">No quests have been reported today.</p>';
    $$('#questFilterOptions [data-quest-keys]').forEach(box=>{box.indeterminate=box.dataset.partial==="true";box.addEventListener("change",applyQuestFilters)});$$('#questFilterOptions [data-reward-key]').forEach(parent=>{parent.addEventListener("click",event=>event.stopPropagation());parent.addEventListener("change",()=>{parent.closest('.reward-filter-group').querySelectorAll('[data-quest-keys]').forEach(box=>{box.checked=parent.checked;box.indeterminate=false});applyQuestFilters()})});$("#showUnreported").onchange=applyQuestFilters;syncRewardGroups();filterQuestOptions();updateQuestFilterButton()
  }
  let turnstileWidget;
  async function openReport(){closeSheet();$("#reportStop").textContent=state.selected.name;fillTasks();$("#reportDialog").showModal();if(CONFIG.turnstileSiteKey){$("#turnstileContainer").classList.remove("hidden");for(let i=0;i<30&&!window.turnstile;i++)await new Promise(resolve=>setTimeout(resolve,100));if(window.turnstile){if(turnstileWidget===undefined)turnstileWidget=turnstile.render("#turnstileContainer",{sitekey:CONFIG.turnstileSiteKey,theme:"dark"});else turnstile.reset(turnstileWidget)}}}
  let visibleController;
  async function loadVisible(){visibleController?.abort();const controller=new AbortController();visibleController=controller;const b=map.getBounds();try{state.pois=await api(`/api/pois?minLat=${b.getSouth()}&maxLat=${b.getNorth()}&minLng=${b.getWest()}&maxLng=${b.getEast()}`,{signal:controller.signal});if(controller.signal.aborted)return;renderPois();clearWarn()}catch(e){if(e.name==="AbortError")return;if(!CONFIG.nianticFrontendFallback){warn(e.message);return}try{state.pois=await loadNianticPois(b,controller.signal);if(controller.signal.aborted)return;renderPois();clearWarn()}catch(fallbackError){if(fallbackError.name==="AbortError")return;if(/zoom in/i.test(fallbackError.message)){state.pois=[];renderPois();warn("Zoom in");return}warn(`POI API failed · GraphQL fallback failed: ${fallbackError.message}`)}}}
  async function loadNianticPois(bounds,signal){
    const ids=frontendS2CellIds(bounds);
    if(!ids.length||ids.length>128)throw new Error("zoom in before using the fallback");const cacheKey=ids.slice().sort().join(","),cached=nianticCache.get(cacheKey);if(cached&&cached.expires>Date.now())return cached.pois.filter(p=>bounds.contains([p.latitude,p.longitude]));
    const sourcesByS2Cells=ids.map(s2CellId=>({s2CellId,sources:[{name:"PGO",dropTypes:["PGO_GYM","PGO_POKESTOP"]}]}));
    const response=await fetch(CONFIG.nianticGraphqlUrl,{method:"POST",mode:"cors",credentials:"omit",signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({query:NIANTIC_QUERY,variables:{input:{realityChannelId:CONFIG.nianticRealityChannelId,s2CellLevel:14,sourcesByS2Cells}}})});
    if(!response.ok)throw new Error(`Niantic returned HTTP ${response.status}`);const payload=await response.json();if(payload.errors?.length)throw new Error("Niantic returned GraphQL errors");const rows=payload.data?.realityChannelMapObjectsByS2Cells?.mapObjectsByS2CellsAndTypes;if(!Array.isArray(rows))throw new Error("unexpected Niantic response");
    const found=new Map(),seen=new Date().toISOString();for(const cell of rows)for(const group of cell.mapObjectsByType||[]){const type=group.type==="PGO_GYM"?"GYM":group.type==="PGO_POKESTOP"?"POKESTOP":null;if(!type)continue;const field=type==="GYM"?"pgoGym":"pgoPokestop";for(const object of group.mapObjects||[]){const data=object[field],location=data?.location;if(!object.id||!location)continue;const p={id:object.id,type,name:data.name||`Unnamed ${type}`,latitude:Number(location.latitude),longitude:Number(location.longitude),lastSeen:seen,s2Level17:"",s2Level14:BigInt(cell.s2CellId).toString(16).replace(/0+$/,"")};found.set(p.id,p)}}const pois=[...found.values()];nianticCache.set(cacheKey,{expires:Date.now()+120000,pois});if(nianticCache.size>20)nianticCache.delete(nianticCache.keys().next().value);return pois.filter(p=>bounds.contains([p.latitude,p.longitude]))
  }
  function frontendS2CellIds(bounds){if(!window.S2?.latLngToKey)throw new Error("S2 browser library did not load");const latSpan=bounds.getNorth()-bounds.getSouth(),lngSpan=bounds.getEast()-bounds.getWest();const rows=Math.max(1,Math.ceil(latSpan/.002)),cols=Math.max(1,Math.ceil(lngSpan/.003));if(rows>60||cols>60)throw new Error("zoom in before using the fallback");const ids=new Set();for(let y=0;y<=rows;y++)for(let x=0;x<=cols;x++){const lat=bounds.getSouth()+latSpan*y/rows,lng=bounds.getWest()+lngSpan*x/cols;ids.add(S2.keyToId(S2.latLngToKey(lat,lng,14)))}return [...ids]}
  function updatePlannerDetailAvailability(){const unavailable=map.getZoom()<15;for(const id of ["#l17","#radius20"]){const input=$(id);input.disabled=unavailable;input.closest("label").classList.toggle("zoom-required",unavailable)}$("#l17Hint").textContent=unavailable?"Zoom in for detail":""}
  function visibleS2Cells(bounds,level){if(!window.S2?.S2Cell?.FromLatLng)throw new Error("S2 browser library did not load");const center=bounds.getCenter(),first=S2.S2Cell.FromLatLng({lat:center.lat,lng:center.lng},level),queue=[first],queued=new Set([first.toHilbertQuadkey()]),cells=[];for(let i=0;i<queue.length;i++){const cell=queue[i],polygon=cell.getCornerLatLngs().map(point=>[point.lat,point.lng]);if(!L.latLngBounds(polygon).intersects(bounds))continue;cells.push(polygon);if(cells.length>15000)throw new Error(`Zoom in to show Level ${level} cells`);for(const neighbor of cell.getNeighbors()){const key=neighbor.toHilbertQuadkey();if(!queued.has(key)){queued.add(key);queue.push(neighbor)}}}return cells}
  function loadCells(){cells17.clearLayers();cells14.clearLayers();updatePlannerDetailAvailability();if(state.mode!=="planner")return;const bounds=map.getBounds();for(const [level,layer,color,box] of [[17,cells17,"#4dbdff","#l17"],[14,cells14,"#ffbd59","#l14"]]){if(!$(box).checked||$(box).disabled)continue;try{const polygons=visibleS2Cells(bounds,level);if(polygons.length)L.polygon(polygons.map(polygon=>[polygon]),{renderer:cellRenderer,color,weight:level===17?1:2,fillOpacity:0,opacity:level===17?.45:.8,interactive:false}).addTo(layer)}catch(e){if(level===17)warn(e.message)}}}
  async function loadStatic(){
    let catalogue;
    try{catalogue=await reportApi("/api/research/catalogue")}catch{try{catalogue={tasks:await loadScrapedDuckCatalogue(),stale:false};toast("Tasks loaded directly from ScrapedDuck")}catch(e){warn(`Task catalogue unavailable · ${e.message}`)}}
    if(catalogue?.tasks?.length){
      if(catalogue.tasks.some(task=>task.rewards?.some(reward=>!reward.image)))try{const artworkTasks=await loadScrapedDuckCatalogue(),artwork=new Map();for(const task of artworkTasks)for(const reward of task.rewards||[])if(reward.image)artwork.set(`${task.id}::${reward.id}`,reward.image);for(const task of catalogue.tasks)for(const reward of task.rewards||[])reward.image||=artwork.get(`${task.id}::${reward.id}`)}catch{}
      state.catalogue=catalogue.tasks;
    }
    try{const reports=await reportApi("/api/research"),grouped=new Map();for(const report of reports){if(!grouped.has(report.pokestopId))grouped.set(report.pokestopId,[]);grouped.get(report.pokestopId).push(report)}state.reportsByStop=grouped;renderQuestFilters();renderPois()}catch(e){if(!state.catalogue.length)warn(`Report service unavailable · ${e.message}`)}
    try{const stats=await reportApi("/api/stats");const nums=[stats.reports_submitted,stats.unique_pokestops_reported,stats.confirmations,stats.conflicting_reports];$$('#stats strong').forEach((el,i)=>el.textContent=nums[i]||0);$("#progressButton").textContent=`Today · ${stats.unique_pokestops_reported||0} stops`}catch(e){if(!state.catalogue.length)warn(`Report service unavailable · ${e.message}`)}
  }
  async function loadScrapedDuckCatalogue(){const cacheKey="pokemap-research-catalogue-v2";try{const response=await fetch(CONFIG.scrapedDuckResearchUrl,{cache:"no-store",credentials:"omit"});if(!response.ok)throw new Error(`ScrapedDuck returned HTTP ${response.status}`);const rows=await response.json();if(!Array.isArray(rows))throw new Error("unexpected ScrapedDuck response");const tasks=rows.map((row,index)=>{const raw=String(row.text||"").trim(),seen=new Set();const rewards=(Array.isArray(row.rewards)?row.rewards:[]).map(reward=>{const label=String(reward.name||reward.label||"").trim(),id=slug(label),image=String(reward.image||"").trim();if(!label||!id||seen.has(id))return null;seen.add(id);return{id,label,type:"ENCOUNTER",...(image.startsWith("https://cdn.leekduck.com/")?{image}:{})}}).filter(Boolean);return raw&&rewards.length?{id:`${slug(raw)}-${index}`,text:plainText(raw),category:"research",rewards}:null}).filter(Boolean);if(!tasks.length)throw new Error("ScrapedDuck returned no tasks");localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),tasks}));return tasks}catch(error){try{const cached=JSON.parse(localStorage.getItem(cacheKey));if(cached?.tasks?.length)return cached.tasks}catch{}throw error}}
  function warn(text){$("#warning").textContent=text;$("#warning").classList.remove("hidden")}function clearWarn(){$("#warning").textContent="";$("#warning").classList.add("hidden")}function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
  let moveTimer,renderedZoom=map.getZoom();map.on("movestart",()=>visibleController?.abort());map.on("moveend",()=>{saveView();updatePlannerDetailAvailability();if(map.getZoom()!==renderedZoom){renderedZoom=map.getZoom();renderPois()}if(state.mode==="planner")loadCells();clearTimeout(moveTimer);moveTimer=setTimeout(loadVisible,250)});
  $$(".modes button").forEach(b=>b.addEventListener("click",()=>{$$(".modes button").forEach(x=>x.classList.toggle("active",x===b));state.mode=b.dataset.mode;document.body.classList.toggle("planner",state.mode==="planner");$("#modeTitle").textContent=state.mode==="planner"?"Inspect S2 cells":"Find today’s research";$("#modeCopy").textContent=state.mode==="planner"?"Use S2 overlays and 20 m spacing guides to evaluate Wayspot locations.":"Tap a PokéStop to view or report its current Field Research.";closeSheet();if(state.mode==="planner"&&map.getZoom()<15)map.setZoom(15);else{renderPois();loadCells()}}));
  $$("[data-filter],#l17,#l14,#radius20").forEach(x=>x.addEventListener("change",()=>{renderPois();loadCells()}));$("#search").addEventListener("input",renderPois);$("#sheetBackdrop").addEventListener("click",closeSheet);$("#taskSelect").addEventListener("change",fillRewards);$("#refresh").addEventListener("click",()=>{loadVisible();loadStatic()});
  $("#questFilterButton").addEventListener("click",()=>{renderQuestFilters();$("#questFilterDialog").showModal()});
  $("#questFilterSearch").addEventListener("input",filterQuestOptions);
  $("#showAllQuests").addEventListener("click",()=>{$$("#questFilterOptions [data-quest-keys]").forEach(box=>{box.checked=true;box.indeterminate=false});$("#showUnreported").checked=true;applyQuestFilters()});
  $("#locate").addEventListener("click",()=>map.locate({setView:true,maxZoom:17,enableHighAccuracy:true}));map.on("locationerror",()=>toast("Location unavailable — showing Antwerp"));
  $("#submitReport").addEventListener("click",async e=>{e.preventDefault();try{const turnstileToken=turnstileWidget===undefined?null:turnstile.getResponse(turnstileWidget);await reportApi("/api/research/report",{method:"POST",body:JSON.stringify({pokestopId:state.selected.id,taskId:$("#taskSelect").value,rewardId:$("#rewardSelect").value,latitude:state.selected.latitude,longitude:state.selected.longitude,turnstileToken})});$("#reportDialog").close();toast("Research reported — thank you!");loadStatic();openPoi(state.selected)}catch(err){toast(err.message);if(turnstileWidget!==undefined)turnstile.reset(turnstileWidget)}});
  updatePlannerDetailAvailability();renderQuestFilters();loadVisible();loadStatic();
})();
